title: GPT Turbo Schedule
description: This is an updated simple test add-on
instructions: This is a sample instruction.
type: object
documents:
  - query
  - selected
properties:
  name:
    title: Name
    type: string
categories: 
  - file
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
version: 2