title: "GPT 3.5 Turbo Scheduler"
description: "Run the GPT 3.5 Turbo Add-On on a batch of documents using a schedule" 
instructions: ''
type: object
properties:
  batch_size:
    title: Batch size
    type: integer
  project_id:
    title: Project ID
    type: integer
  key_name:
    title: Key
    type: string
required:
  - batch_size
  - project_id
  - key_name
categories:
  - ai