title: "GPT 3.5 Turbo Scheduler"
description: "Run the GPT 3.5 Turbo Add-On on a batch of documents using a schedule" 
instructions: ''
type: object
documents: []
properties:
  batch_size:
    title: 'Batch size'
    type: integer
    description: "How many documents do you want analyzed per scheduled run?"
  project_id:
    title: "Project ID"
    type: integer
    description: "Project ID of the project you would like to run this on." 
  key_name:
    title: "Key"
    type: string
    description: "The name of the key you are using to label the documents with"
  prompt:
    title: "Prompt"
    type: string
    description: "GPT 3.5 Turbo Prompt you want to run on each batch of documents"
required:
  - batch_size
  - project_id
  - key_name
  - prompt
eventOptions:
  name: gpt
  events:
    - hourly
    - daily
    - weekly