title: "GPT 3.5 Turbo Scheduler"
description: "Run the GPT 3.5 Turbo Add-On on a batch of documents using a schedule" 
instructions: ''
type: object
documents: []
properties:
  batch_size:
    title: 'Batch size'
    type: integer
    default: 100
    description: "How many documents do you want analyzed per scheduled run?"
  project_id:
    title: "Project ID"
    type: integer
    description: "Project ID of the project you would like to run this on." 
  key_name:
    title: "Key"
    type: string
    description: "The name of the key you are using to label the documents with"
  filter_key:
    title: "Filter Key"
    type: string
    description: "If you need to narrow down the document set further, provide a key name you want to filter by. If value isn't also specified, then it will filter on any documents that have that key."
  filter_value:
    title: "Filter Value"
    type: string
    description: "If you want to provide a specific key/value pair to narrow on, provide the value here and the key in filter key. "
  prompt:
    title: "Prompt"
    type: string
    description: "GPT 3.5 Turbo Prompt you want to run on each batch of documents"
  limiter:
    title: "Limiter"
    type: integer
    minimum: 1000
    maximum: 56000
    default: 20000
    description: "Number of tokens to limit the GPT prompt on"
required:
  - batch_size
  - project_id
  - key_name
  - prompt
eventOptions:
  name: gpt
  events:
    - hourly
    - daily
    - weekly
categories:
  - ai
  - premium
